image: node:latest

#include:
#  - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - node_modules/
  
build-job:
    stage: build
    script:
        - npm install
        - npm build
    artifacts:
        paths:
            - build/

test-job1:
    stage: test
    script:
        - echo "SAST testing"

pages:
    stage: deploy
    cache:
        paths:
            - node_modules/

    script:
        - rm -rf public
        - cp build/index.html build/404.html
        - mv build public

    artifacts:
        paths:
            - public

    only:
       - master
            
    after_script:
        - echo "finished"
        - ls
        - bash ./telegram_notification.sh


