image: node:latest

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - npm
  - build-job
  - test-job1
  - deploy-prod

npm:
  stage: npm
  script:
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
  
build-job:
    stage: build
    script:
        - node

test-job1:
    stage: test
    script:
        - npm test

deploy-prod:
    stage: deploy
    script:
        - echo "finished"




