image: node:latest

include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - echo "SAST testing"

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
<<<<<<< HEAD
=======
  only:
    - main

>>>>>>> 9b934806d10946f9c3f3f49be115a5fc2070e468
