image: node:latest

include:
  - template: Security/SAST.gitlab-ci.yml
  
build-job:
    stage: build
    script:
        - node

test-job1:
    stage: test
    script:
        - echo "SAST testing"

deploy-prod:
    stage: deploy
    script:
        - npm run deploy
    after_script:
        - echo "finished"
        - ls
        - bash ./telegram_notification.sh


