image: node:latest

include:
  - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - node_modules/
  
build-job:
    stage: build
    script:
        - npm install

    artifacts:
        paths:
            - node_modules/

test-job1:
    stage: test
    script:
        - echo "SAST testing"

deploy-prod:
    stage: deploy
    script:
        - git config --global user.email "gabriela.gondo@hotmail.com"
        - git config --global user.name "Gabriela Gondo"
        - npm run deploy

    artifacts:
        paths:
            - node_modules/
            
    after_script:
        - echo "finished"
        - ls
        - bash ./telegram_notification.sh


