image: node:latest

include:
  - template: Security/SAST.gitlab-ci.yml
  
build-job:
    stage: build
    script:
        - node

test-job1:
    stage: test
    script:
        - echo "testing"

deploy-prod:
    stage: deploy
    script:
        - echo "finished"




