image: node:latest

build-job:
    stage: build
    script:
        - node

test-job1:
    stage: test
    script:
        - npm start

deploy-prod:
    stage: deploy
    script:
        - echo "finished"




